version: "3"

services:
  vote:
    build: ./vote
    ports:
      - "5000:80"

  result:
    build: ./result
    ports:
      - "5001:80"

  worker:
    build:
      context: ./worker
    depends_on:
      - "redis"
      - "db"

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data:
